// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: hello-grpc.proto

package grpc_hello_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HelloGrpcService_GetData_FullMethodName = "/hello_grpc.HelloGrpcService/GetData"
)

// HelloGrpcServiceClient is the client API for HelloGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloGrpcServiceClient interface {
	GetData(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type helloGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloGrpcServiceClient(cc grpc.ClientConnInterface) HelloGrpcServiceClient {
	return &helloGrpcServiceClient{cc}
}

func (c *helloGrpcServiceClient) GetData(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, HelloGrpcService_GetData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloGrpcServiceServer is the server API for HelloGrpcService service.
// All implementations should embed UnimplementedHelloGrpcServiceServer
// for forward compatibility
type HelloGrpcServiceServer interface {
	GetData(context.Context, *Message) (*Message, error)
}

// UnimplementedHelloGrpcServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHelloGrpcServiceServer struct {
}

func (UnimplementedHelloGrpcServiceServer) GetData(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}

// UnsafeHelloGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloGrpcServiceServer will
// result in compilation errors.
type UnsafeHelloGrpcServiceServer interface {
	mustEmbedUnimplementedHelloGrpcServiceServer()
}

func RegisterHelloGrpcServiceServer(s grpc.ServiceRegistrar, srv HelloGrpcServiceServer) {
	s.RegisterService(&HelloGrpcService_ServiceDesc, srv)
}

func _HelloGrpcService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloGrpcServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloGrpcService_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloGrpcServiceServer).GetData(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloGrpcService_ServiceDesc is the grpc.ServiceDesc for HelloGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello_grpc.HelloGrpcService",
	HandlerType: (*HelloGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _HelloGrpcService_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello-grpc.proto",
}
